# Generated by Django 5.0.6 on 2024-07-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='code_pin',
        ),
    ]
