# Generated by Django 5.0.6 on 2024-06-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_gerant',
        ),
    ]
