# Generated by Django 5.0.6 on 2024-07-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_solde_alter_utilisateur_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='solde',
        ),
    ]
